"""ROI calculation for promotional campaigns."""

from __future__ import annotations


class ROIScorer:
    """Calculate return on investment for promotional activities."""

    def __init__(self) -> None:
        """Initialize the ROIScorer."""
        self._roi_cache: dict[str, float] = {}

    def calculate_roi(
        self,
        incremental_revenue: float,
        promo_cost: float,
        campaign_id: str | None = None,
    ) -> float:
        """
        Calculate ROI for a promotional campaign.

        Args:
            incremental_revenue: Additional revenue generated by promotion.
            promo_cost: Total cost of the promotion.
            campaign_id: Optional campaign identifier for caching.

        Returns:
            ROI as percentage ((revenue - cost) / cost * 100).
        """
        if promo_cost <= 0:
            return 0.0

        roi = ((incremental_revenue - promo_cost) / promo_cost) * 100

        if campaign_id:
            self._roi_cache[campaign_id] = roi

        return roi

    def get_roi(self, campaign_id: str) -> float:
        """
        Retrieve cached ROI.

        Args:
            campaign_id: Campaign identifier.

        Returns:
            Cached ROI or 0.0 if not computed.
        """
        return self._roi_cache.get(campaign_id, 0.0)

    def clear_cache(self) -> None:
        """Clear cached ROI values."""
        self._roi_cache.clear()
